version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db_mysql5.7
    ports:
      - 3336:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: exchange_app
    tty: true
    volumes:
      - ./:/go/src
    ports:
      - 8080:8080
    depends_on:
      - db
